apiVersion: 1

groups:
  - orgId: 1
    name: MuskratTrapAlerts
    folder: "MuskratTrap Alerts"
    interval: 1m
    rules:
      - uid: trap_low_battery
        title: TrapLowBattery
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: 'deodcfz2cewhsd'
            model:
              rawSql: |
                SELECT
                  devID AS devID_label,
                  batteryStatus AS trap_battery_level
                FROM trap_data td1
                WHERE td1.timestamp = (
                  SELECT MAX(td2.timestamp)
                  FROM trap_data td2
                  WHERE td2.devID = td1.devID
                );
              format: table
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: '__expr__'
            model:
              type: threshold
              conditions:
                - evaluator:
                    params:
                      - 20
                    type: lt
                  operator:
                    type: and
              expression: A
        noDataState: OK
        execErrState: Error
        for: 5m
        isPaused: false
        labels:
          severity: warning
        annotations:
          summary: 'Low battery in trap {{ $labels.devID_label }}'
          description: 'Trap {{ $labels.devID_label }} has a low battery level ({{ $values.trap_battery_level }}%). Please schedule maintenance.'
