apiVersion: 1

groups:
  - orgId: 1
    name: MuskratTrapAlerts
    folder: "MuskratTrap Alerts"
    interval: 1m
    rules:
      - uid: trap_offline
        title: TrapOffline
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 90000
              to: 0
            datasourceUid: 'deodcfz2cewhsd'
            model:
              rawSql: |
                SELECT
                  devID AS devID_label,
                  MAX(timestamp) AS last_seen_timestamp,
                  (UNIX_TIMESTAMP(NOW()) - UNIX_TIMESTAMP(MAX(timestamp))) AS time_since_last_report_seconds
                FROM trap_data
                GROUP BY devID
                HAVING (UNIX_TIMESTAMP(NOW()) - UNIX_TIMESTAMP(MAX(timestamp))) > 90000;
              format: table
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            relativeTimeRange:
              from: 90000
              to: 0
            datasourceUid: '__expr__'
            model:
              type: threshold
              conditions:
                - evaluator:
                    params:
                      - 90000
                    type: gt
                  operator:
                    type: and
              expression: A
        noDataState: OK
        execErrState: Error
        for: 10m
        isPaused: false
        labels:
          severity: warning
        annotations:
          summary: 'Trap {{ $labels.devID_label }} may be offline'
          description: 'Trap {{ $labels.devID_label }} has not reported data for more than 25 hours. Last seen at {{ $labels.last_seen_timestamp }}.'
